skips:
  # Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
  # => OK, we don't care though
  - B101
  # B305:blacklist - Use of insecure cipher mode cryptography.hazmat.primitives.ciphers.modes.ECB.
  # Need to bypass this check because the PDF specification demands the use of ECB mode on one of the encryption algorithms
  - B305
