from pathlib import Path

import pytest

from fpdf import FPDF
from test.utilities import assert_pdf_equal

HERE = Path(__file__).resolve().parent


def test_add_font_non_existing_file():
    pdf = FPDF()
    with pytest.raises(FileNotFoundError) as error:
        pdf.add_font("non-existing")
    expected_msg = "[Errno 2] No such file or directory: 'non-existing.pkl'"
    assert str(error.value) == expected_msg


def test_add_font_non_existing_file_unicode():
    pdf = FPDF()
    with pytest.raises(FileNotFoundError) as error:
        pdf.add_font("non-existing", uni=True)
    expected_msg = "TTF Font file not found: non-existing.pkl"
    assert str(error.value) == expected_msg


def test_add_font_unicode(tmp_path):
    pdf = FPDF()
    font_file_path = HERE / "../end_to_end_legacy/charmap/Roboto-Regular.ttf"
    pdf.add_font("Roboto", fname=font_file_path, uni=True)
    pdf.set_font("Roboto", size=64)
    pdf.add_page()
    pdf.cell(pdf.epw, 20, "Hello World!")
    assert_pdf_equal(pdf, HERE / "add_font_unicode.pdf", tmp_path)


def test_add_font_from_pkl(tmp_path):
    pdf = FPDF()
    font_file_path = HERE / "../end_to_end_legacy/charmap/Roboto-Regular.ttf"
    pdf.add_font("Roboto", fname=font_file_path, uni=True)
    pdf.add_font("Roboto")  # re-using .pkl file generated by previous method call
    pdf.set_font("Roboto", size=64)
    pdf.add_page()
    pdf.cell(pdf.epw, 20, "Hello World!")
    assert_pdf_equal(pdf, HERE / "add_font_from_pkl.pdf", tmp_path)
